### ISSUE TITLE
espocrm-daemon exited with code 0

### ISSUE THREAD

**Issue by vp-lab** [espocrm/espocrm-docker#14]
Hello,

After upgrading to 7.1.7 from 7.0.10, the espocrm-daemon it's in restarting loop with this error: 
```espocrm-daemon exited with code 0```
![2022-06-21_15-52](https://user-images.githubusercontent.com/18114871/174804843-e72643c2-5694-4fc9-b118-567e07c53dac.png)

After the update we get:
```
Attaching to espocrm, espocrm-daemon
espocrm         | Run "upgrade" action.
espocrm         | Start upgrading process from version 7.0.10.
espocrm         | Upgrade process is finished. EspoCRM version is 7.1.7.
```
But the daemon it's in a restarting loop.

It's there a path to make the update to the latest version ?

Thank you.

**Comment by tmachyshyn** [comment]
Hello,

Please check your EspoCRM log file for more details, https://docs.espocrm.com/administration/log/#default-log.

**Comment by tmachyshyn** [comment]
This issue was related to the configuration bug, https://github.com/espocrm/espocrm-docker/commit/6cfd3234991f48475916aafd85eb017c9e5a447d.
Thanks everyone to help fix it.
