### ISSUE TITLE
database port

### ISSUE THREAD

**Issue by karkaaa** [espocrm/espocrm-docker#15]
Hello,

It is possible in docker compose insert other espo crm database port?

like this:
    environment:
      ESPOCRM_DATABASE_HOST: mysql
      ESPOCRM_DATABASE_PORT: 3307
      ESPOCRM_DATABASE_USER: espocrm
      
I see in data/config-internal.php:
'database' => [
    'driver' => 'pdo_mysql',
    'dbname' => 'YOUR_DATABASE_NAME',
    'user' => 'YOUR_USER',
    'password' => 'YOUR_DATABASE_PASSWORD',
    'host' => 'localhost',
    '**port**' => '',
],

Thank you.

**Comment by jasonheffner** [comment]
Have you tried ESPOCRM_DATABASE_HOST as mysql:3307 ? I think that may be the way it's implemented.

**Comment by tmachyshyn** [comment]
You can also, use `ESPOCRM_DATABASE_HOST` option in the format:

```
ESPOCRM_DATABASE_HOST: "mysql:3307"
```
