### ISSUE TITLE
Apple Silicon Support

### ISSUE THREAD

**Issue by kczereczon** [espocrm/espocrm-docker#18]
According to this conversation with Yuri I found out missing arm64 arch support I've tried to create own docker image for arm64 but I've stuck with PhantomJS missing binary, but problem has probably gone https://github.com/espocrm/espocrm/issues/2538

I need arm64 need for dockerization of dev env

**Comment by tmachyshyn** [comment]
Arm64 platform is added https://github.com/espocrm/espocrm-docker/commit/3331b1086c345f311f0b041f38043dd7d5451b55.
It's already available in the latest version 7.3.2 on [dockerhub](https://hub.docker.com/r/espocrm/espocrm/tags?page=1).
