### ISSUE TITLE
Bug: Jobs Run in Parallel not compatible with 7.3.2

### ISSUE THREAD

**Issue by Nibreos** [espocrm/espocrm-docker#20]
Release: 7.3.2 in Docker.

I updated from 7.2.7 to 7.3.2 and found that no Scheduled Jobs were running (Check Group Email Accounts & Run Scheduled Workflows specifically).

Issues subsided after un-checking :  _Job Settings > "Jobs Run in Parallel"_ 

In html/data/logs is:

> `WARNING: Cron is not run because it's disabled with 'cronDisabled' param. [] []`
> 
> `ERROR: Uncaught Exception Spatie\Async\Output\ParallelError: "PHP Deprecated:  Opis\Closure\SerializableClosure implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /var/www/html/vendor/opis/closure/src/SerializableClosure.php on line 18 " at /var/www/html/vendor/spatie/async/src/Output/ParallelError.php line 11 {"exception":"[object] (Spatie\\Async\\Output\\ParallelError(code: 0): PHP Deprecated:  Opis\\Closure\\SerializableClosure implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /var/www/html/vendor/opis/closure/src/SerializableClosure.php on line 18\n at /var/www/html/vendor/spatie/async/src/Output/ParallelError.php:11)"} []`

May have something todo with dropping PHP 7.4 support in release 7.3.0?

Related? https://github.com/espocrm/espocrm/issues/1283  & [Forum Post](https://forum.espocrm.com/forum/installation-and-upgrade-help/62312-parallel-processing-of-jobs-uncaught-exception-spatie-async-output-parallelerror)

It would be nice to be able to use "Jobs run in parallel" as it [sounds like it is highly recommended](https://docs.espocrm.com/administration/jobs/#setting-up).

**Comment by lazespo** [comment]
Hi @Nibreos and @kennhardy,

This issue has been fixed in EspoCRM 7.3.3. Please upgrade your instance to at least version 7.3.3 (latest version is 7.3.4) and test the work of Scheduled Jobs with Jobs Run in Parallel function enabled.
Note that the same issue was described on the forum and was soon fixed:
https://forum.espocrm.com/forum/general/87817-error-log-opis-closure-serializableclosure-implements-the-serializable-interface.
