### ISSUE TITLE
How does 'charset' end up NULL in data/config-internal.php by default?

### ISSUE THREAD

**Issue by digitalextremist** [espocrm/espocrm-docker#25]
As discovered in this issue: https://github.com/espocrm/espocrm/issues/2758

In my last 5 instances of deploying `EspoCRM` using the docker implementation,`data/config-internal.php` ended up with `charset` being stored as `NULL` which then broke emojis across the board. `Error 500` and then in the log:

```
ERROR: (HY000) SQLSTATE[HY000]: General error: 1366 Incorrect string value:
```

---

Posting this here for myself unless someone answers it and corrects the implementation before me.

**Comment by lazespo** [comment]
Could you please clarify which emojis cause the error 500 in your instances? Also, clarify under what conditions this happens: whether the fields of some records are filled in by emojis or, for example, they are in the body or subject of the email.

Please note that `charset` option is set to NULL in the instance configuration not only in the Docker environment, but also during EspoCRM usage directly on the server (e.g., installation in the */var/www/* directory).
