### ISSUE TITLE
Set debug logging through Config Environments

### ISSUE THREAD

**Issue by fdstevex** [espocrm/espocrm-docker#26]
I'm trying to work through installing on Kubernetes, and I'm at a point where enabling debug logging would be useful.

I can override values in config.php using Config Environments (https://docs.espocrm.com/administration/log/) but the `logger` setting is an array, and there's no example of how to do this. 

Is it possible to set an array config value from the environment?

**Comment by tmachyshyn** [comment]
You can define the following environment (since v8.2.1):

```
ESPOCRM_CONFIG_LOGGER_LEVEL: "DEBUG"
```

For more details, please visit https://docs.espocrm.com/administration/docker/installation/#config-environments
