### ISSUE TITLE
SMTP configuration in docker-compose environment ?

### ISSUE THREAD

**Issue by dac11011** [espocrm/espocrm-docker#30]
It would be nice if we could add the outgoing mail / SMTP configuration in the environment for the docker-compose.  Something like SMTP_HOST, SMTP_USER, SMTP_PASS, so this can be set here instead of having to configure it manually in the webgui.

Same thing with LDAP settings.

**Comment by arkadiyasuratov** [comment]
You can set values for string, int, and bool types using the `ESPOCRM_CONFIG_` prefix. For example, the configuration parameter `ldapUserFirstNameAttribute` becomes `ESPOCRM_CONFIG_LDAP_USER_FIRST_NAME_ATTRIBUTE: 'givenName'`, and `smtpPort` becomes `ESPOCRM_CONFIG_SMTP_PORT: '587'`.

**Comment by dac11011** [comment]
Confirmed this is working.  Thanks!

**Comment by epthewizard** [comment]
> Confirmed this is working.  Thanks!

I cannot get smtp outgoing to authenticate for the life of me. Whenever I try to send a test email I get an unknown error. Is there anything I can try to get it going? I mapped port 465 from the container to my host as well

**Comment by arkadiyasuratov** [comment]
You don't need port mapping. Are you using `localhost` or `127.0.0.1` as your SMTP host?

**Comment by epthewizard** [comment]
I figured it out, it was a stupid mistake. This is the best CRM I've tried self hosting btw, great work
