### ISSUE TITLE
PostgreSQL support broken

### ISSUE THREAD

**Issue by sourcecodes2** [espocrm/espocrm-docker#32]
PostgreSQL support is currently broken due to no system libraries or PDO drivers installed inside the Debian or Alpine images.

![espocrm-postgresql](https://github.com/espocrm/espocrm-docker/assets/202094/a2d91172-b79e-459c-86e7-56ee1e4b4f7a)

Required libraries:
- Debian: `libpq-dev`
- Alpine: `postgresql-dev`

Required PHP extension:
- `pdo_pgsql`

Created pull request #31 with fixes for all images.

[CLA signed](https://github.com/espocrm/cla/blob/master/contributors/sourcecodes2.md)

**Comment by tmachyshyn** [comment]
PostgreSQL support has been added since EspoCRM v8.2.0.
