### ISSUE TITLE
Missing releases

### ISSUE THREAD

**Issue by Zelphy** [espocrm/espocrm-docker#36]
Hello,

Similar to #29, latest releases are not available via DockerHub (8.1.1 → 8.1.3)

As a workaround, I can trigger the upgrade manually in the container via `docker exec -i espocrm php bin/command upgrade -y`

Regards.

**Comment by tmachyshyn** [comment]
The releases 8.1.1 - 8.1.3 have been added on DockerHub on Feb 3, 2024.
