### ISSUE TITLE
Unable to upgrade 8.06 to 8.1.4

### ISSUE THREAD

**Issue by skorvek** [espocrm/espocrm-docker#37]
I am running EspoCRM on docker via Portainer. I've had a working system for quite a while, I've made no recent changes. Today I went to upgrade the stack from from 8.0.6 to 8.1.4. Simple process- go to the stack, stop it, re-pull updated images from the repository and re-deploy.
Logs show "upgrading from 8.06" for 45 minutes with no apparent activity. Exec

`Run "upgrade" action.
Start upgrading process from version 8.0.6.
PHP Warning:  require(/var/www/html/vendor/composer/../../application/Espo/Resources/defaults/tcpdf-config.php): Failed to open stream: No such file or directory in /var/www/html/vendor/composer/autoload_real.php on line 53
PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/vendor/composer/../../application/Espo/Resources/defaults/tcpdf-config.php' (include_path='/var/www/html') in /var/www/html/vendor/composer/autoload_real.php:53
Stack trace:
#0 /var/www/html/vendor/composer/autoload_real.php(36): composerRequire81e67dd04e1d26db73a6b9676f976909('618029bee273295...', '/var/www/html/v...')
#1 /var/www/html/vendor/autoload.php(25): ComposerAutoloaderInit81e67dd04e1d26db73a6b9676f976909::getLoader()
#2 /var/www/html/bootstrap.php(33): require_once('/var/www/html/v...')
#3 /var/www/html/command.php(30): include('/var/www/html/b...')
#4 {main}
  thrown in /var/www/html/vendor/composer/autoload_real.php on line 53`

This is a repeated error until the max upgrade counter limit is reached. The system is not usable at all. I deleted the containers and tried again- same errors. But this time, Apache will "resume normal operations" but the client's still down. Attempts to access it prompt the same error:

`[Fri Mar 01 17:39:28.350972 2024] [php:error] [pid 111] [client 10.2.140.1:58672] PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/vendor/composer/../../application/Espo/Resources/defaults/tcpdf-config.php' (include_path='/var/www/html') in /var/www/html/vendor/composer/autoload_real.php:53\nStack trace:\n#0 /var/www/html/vendor/composer/autoload_real.php(36): composerRequire81e67dd04e1d26db73a6b9676f976909('618029bee273295...', '/var/www/html/v...')\n#1 /var/www/html/vendor/autoload.php(25): ComposerAutoloaderInit81e67dd04e1d26db73a6b9676f976909::getLoader()\n#2 /var/www/html/bootstrap.php(33): require_once('/var/www/html/v...')\n#3 /var/www/html/public/index.php(30): include('/var/www/html/b...')\n#4 {main}\n  thrown in /var/www/html/vendor/composer/autoload_real.php on line 53`

**Comment by lazespo** [comment]
If you are still concerned about this issue, we ask you to let you know about it on the forum in the following topic: https://forum.espocrm.com/forum/installation-and-upgrade-help/103288-broken-docker-installation-after-attempted-upgrade-cannot-locate-tcpdf-config-php.
