### ISSUE TITLE
Please add docker label `org.opencontainers.image.source`

### ISSUE THREAD

**Issue by sschnabe** [espocrm/espocrm-docker#38]
We are using renovate to check for updates and it would be very convenient to have release notes in the dependency-dashboard/commit comments. To enable this the images should have this label ([see renovate docs](https://docs.renovatebot.com/modules/datasource/docker/)):

```Dockerfle
LABEL org.opencontainers.image.source="https://github.com/espocrm/espocrm"
```

More useful labels can be found here: [opencontainers/image-spec](https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys)

**Comment by tmachyshyn** [comment]
Added, https://github.com/espocrm/espocrm-docker/commit/544371acf1b882ba4713a2e6c3004512f3362240.
