### ISSUE TITLE
Fetching emails - cron job in docker

### ISSUE THREAD

**Issue by stef204** [espocrm/espocrm-docker#45]
Running Version 8.2.4 in docker (**not** `docker compose`).

All is working smoothly.

I set up a test personal email account, and connections test OK, test email gets sent properly, etc.

How do I set up a cron job inside the container so that emails get fetched?  I looked at the instructions but cannot seem to apply them to using espocrm inside docker container.

I can fire up a shell using `docker exec -it espocrm bash` and `docker exec -it espocrm bash -c "pgrep cron"` returns nothing.

The admin portal gives this message:

```
Scheduled jobs are not running. Hence inbound emails, notifications and reminders are not working. Please follow the instructions to setup cron job.
```
Clueless here.  Just getting started with docker so bear with me please.

Note 1: If there is a way to retrieve emails manually, without using a cron job, I might go that route, but I do not think it is possible with espocrm.

Note 2: I tried to fire up a shell and once in, I can see the `cron.php` file.  ~~If I then go: `php -f cron.php​` I get this error message: `Could not open input file: cron.php​`~~

~~I'd usually think it's a permission problem but I'm logged in as `root@........` and `pwd` is `/var/www/html`.~~

I think my shell was not inserting the characters of the file name correctly when typing it, for some reason.  Using tab completion, the error message above disappeared after running `php -f cron.php​`. Can't see any `cron` process running but the message to `setup cron job` (above) is now gone.

**Comment by lazespo** [comment]
Hi @stef204,

Please tell me have you tried to add the following line to the crontab as a root user?
```
* * * * * /usr/bin/docker exec --user www-data -i espocrm /bin/bash -c "cd /var/www/html; /usr/local/bin/php -f cron.php" > /dev/null 2>&1
```

**Comment by stef204** [comment]
@lazespo of course I have looked into it.  But I fail to see HOW to add this to the crontab.

Can you explain how to do this, when using `docker` (not `docker compose`)?

What I have tried is to fire up a shell with: 

`docker exec -it my-espocrm bash` and then using: `crontab -e -u WEBSERVER_USER` but first off, `crontab` is not recognized as a command.

Trying `docker exec -it my-espocrm bash -c crontab -e -u WEBSERVER_USER` same, not recognized.

I understand I need to replace the variable `WEBSERVER_USER` but not completely sure what to use here.  I tried `www` and `www-data` but doesn't matter as the command `crontab` is either not on the `$PATH` or not present.....

Sorry, I am completely new to this.....

Can you explain please?

**Comment by lazespo** [comment]
@stef204,

The command that I suggested needs to be inserted into the crontab directly of the server where you are using Docker, but not into any Docker container itself. 

Please log in to your server as root and enter `crontab -e` command, then a text editor will open where you can paste this command:

```
* * * * * /usr/bin/docker exec --user www-data -i espocrm /bin/bash -c "cd /var/www/html; /usr/local/bin/php -f cron.php" > /dev/null 2>&1
```

**Comment by lazespo** [comment]
@stef204,

I’m glad that I was able to explain this question more clearly.

The daemon is more suitable for using EspoCRM directly on the server (on the host). 
So the best option for you is to insert the previously mentioned line into the server (host) crontab.

**Comment by stef204** [comment]
OK, so I have successfully enabled the cronjob, and it is working; I can see the emails inside espocrm now. Thanks a lot!

I am going to have to open another ticket for replying to emails which is not working. The test email does get sent though.

**Comment by venukotamraju** [comment]
Hi, @lazespo, I am now held up with the same issue. But  I did follow up until setting up the crontab on the server part and I lost you at the same too. As I am using windows and running docker in  it. So I am finding trouble setting up the cronjob as per. For, when I see the article on setting up scheduled tasks in windows, it is a different process and the paths dont match too for what the admin panel is prompting out and that mentioned in the "scheduling jobs in windows" article. Can I get any help with this. I would very much appreciate it, thank you!

**Comment by lazespo** [comment]
Hi @venukotamraju,

You can consider this option of using a Docker container for the daemon (the same cron):

```
docker run --name espocrm-daemon --link espocrm:espocrm -d espocrm/espocrm docker-daemon.sh
```

`espocrm:espocrm` is the main container for EspoCRM; you can replace it if the name of your container is different.

**Comment by venukotamraju** [comment]
Hey @lazespo, thank you so much for your quick response and the suggested fix!

I wanted to share the setup I’ve been using to trigger the `cron.php` file inside Docker from Windows:

1. I created a Windows batch file with the following command and saved it:

> powershell
```shell
docker exec my-espocrm /usr/local/bin/php -f /var/www/html/cron.php *> $null
```  

2. Then, I used Windows Event Scheduler to run this batch file every five minutes daily.

With this setup, email notifications and reminders are being sent successfully and are visible in the external email boxes. However, these emails are not being fetched into the EspoCRM system, even after configuring IMAP and providing a "fetch from" date. Interestingly, emails composed within the system are showing up perfectly.

Does this behavior seem normal to you? And, would the daemon fix address this issue? I’d also love to understand how it fares compared to the setup I mentioned.

Thanks again for your help!


> Hi [@venukotamraju](https://github.com/venukotamraju),
> 
> You can consider this option of using a Docker container for the daemon (the same cron):
> 
> ```
> docker run --name espocrm-daemon --link espocrm:espocrm -d espocrm/espocrm docker-daemon.sh
> ```
> 
> `espocrm:espocrm` is the main container for EspoCRM; you can replace it if the name of your container is different.

**Comment by lazespo** [comment]
@venukotamraju,

Fetching incoming emails depends entirely on a properly configured cron. This is written right above in the article in the documentation: https://docs.espocrm.com/administration/emails.

And sending emails is manual, cron does not play a role here at all.

In general, crontab and daemon are the same things: https://docs.espocrm.com/administration/jobs/#setting-up.

Please note that I have not tested the solution provided to you on Windows, but it works fine in Ubuntu.

**Comment by nmincone** [comment]
> Hi [@venukotamraju](https://github.com/venukotamraju),
> 
> You can consider this option of using a Docker container for the daemon (the same cron):
> 
> ```
> docker run --name espocrm-daemon --link espocrm:espocrm -d espocrm/espocrm docker-daemon.sh
> ```
> 
> `espocrm:espocrm` is the main container for EspoCRM; you can replace it if the name of your container is different.

I've tried this solution but it hasn't worked for me.
`~/docker/espocrm-docker$ docker run --name espocrm-daemon --link espocrm:espocrm -d espocrm/espocrm docker-daemon.sh
docker: Error response from daemon: could not get container for espocrm: No such container: espocrm`

I see in logs;
`espocrm-daemon     | Instance is not ready: waiting for the installation
espocrm-daemon exited with code 0
espocrm-daemon     | Instance is not ready: waiting for the installation
espocrm-daemon exited with code 0`
over and over.

I shut the containers down, added it to crontab, restarted containers.

**Comment by nmincone** [comment]
Hi, it's definitely espocrm and appears to be running.
`
NAMES
badb6a6edc47   espocrm/espocrm   "docker-entrypoint.s…"   23 hours ago    Up 23 hours                     0.0.0.0:3050->80/tcp, [::]:3050->80/tcp                                                                                                                                 espocrm
7da6f07dea31   espocrm/espocrm   "docker-websocket.sh"    23 hours ago    Up 23 hours                     80/tcp, 0.0.0.0:7777->8080/tcp, [::]:7777->8080/tcp                                                                                                                         espocrm-websocket
867f7f8e10da   espocrm/espocrm   "docker-daemon.sh"       23 hours ago    Restarting (0) 12 seconds ago                                                                                                                                                                               espocrm-daemon
4218e2037923   mariadb:latest   "docker-entrypoint.s…"   23 hours ago    Up 23 hours (healthy)           3306/tcp                                                                                                                                                                  espocrm-db

`

I ran both with containers running and not running...
`docker run --name espocrm-daemon --link espocrm:espocrm -d espocrm/espocrm docker-daemon.sh`

Running I get
`docker: Error response from daemon: Conflict. The container name "/espocrm-daemon" is already in use by container "867f7f8e10daa7b1757b956589948782c4e4ad3be100b1f804498fb4eadcb67c". You have to remove (or rename) that container to be able to reuse that name.`

Not running I get
`docker: Error response from daemon: could not get container for espocrm: No such container: espocrm`

Not sure what I'm missing here.

**Comment by nmincone** [comment]
I see, thank you... then why are my logs filling up with 
`espocrm-daemon     | Instance is not ready: waiting for the installation
espocrm-daemon exited with code 0`
What is this daemon error referring to? I assumed it was the email check.

**Comment by lazespo** [comment]
@nmincone,

This is not an error, just monitoring. To make sure that cron is working, go to Administration > Scheduled Jobs > Jobs and view the list of jobs. If there are fresh ones with the status Success, then cron is working fine.

**Comment by nmincone** [comment]
Ok, thanks... Hmmm even though I'm running in Docker, seems like it was working then after I removed the crontab entry seems like it stopped... I guess I need to keep it in crontab?

But still curious why the log shows `espocrm-daemon     | Instance is not ready: waiting for the installation espocrm-daemon exited with code 0` any idea what this daemon is doing and how to get this to stop if it's just monitoring, why the `waiting for the installation espocrm-daemon exited with code 0`?

`Check Personal Email Accounts 	Pending 	Aug 06 09:26:00AM 			Aug 06 09:25:01AM 	
	Check Personal Email Accounts 	**Pending** 	Aug 06 09:26:00AM 			Aug 06 09:25:01AM 	
	Process Job Queue e0 	Success 	Aug 06 09:25:01AM 		Aug 06 09:25:03AM 	Aug 06 09:25:01AM 	
	Process Job Queue q1 	Pending 	Aug 06 09:26:00AM 			Aug 06 09:25:01AM 	
	Process Job Queue q0 	Success 	Aug 06 09:25:01AM 		Aug 06 09:25:03AM 	Aug 06 09:25:01AM 	
	Submit Popup Reminders 	Success 	Aug 06 09:25:01AM 		Aug 06 09:25:03AM 	Aug 06 09:25:01AM 	
	Check Personal Email Accounts 	**Success** 	Aug 06 09:25:00AM 		Aug 06 09:25:03AM 	Aug 06 09:24:02AM 	
	Check Personal Email Accounts 	**Success** 	Aug 06 09:25:00AM 		Aug 06 09:25:02AM 	Aug 06 09:24:02AM 	
	Process Webhook Queue 	Pending 	Aug 06 09:26:00AM 			Aug 06 09:24:02AM 	
	Auth Token Control 	Pending 	Aug 06 09:30:00AM 			Aug 06 09:24:02AM 	
	Send Email Notifications 	Pending 	Aug 06 09:26:00AM 			Aug 06 09:24:02AM 	
	Send Email Reminders 	Pending 	Aug 06 09:26:00AM 			Aug 06 09:24:02AM 	
	Check Group Email Accounts 	Pending 	Aug 06 09:26:00AM 			Aug 06 09:24:02AM 	
	Process Job Queue e0 	Success 	Aug 06 09:24:02AM 		Aug 06 09:24:06AM 	Aug 06 09:24:02AM 	
	Process Job Queue q1 	Success 	Aug 06 09:25:00AM 		Aug 06 09:25:01AM 	Aug 06 09:24:02AM 	
	Process Job Queue q0 	Success 	Aug 06 09:24:02AM 		Aug 06 09:24:06AM 	Aug 06 09:24:02AM 	
	Submit Popup Reminders 	Success 	Aug 06 09:24:02AM 		Aug 06 09:24:06AM 	Aug 06 09:24:02AM 	
	Check Personal Email Accounts 	Success 	Aug 06 09:24:00AM 		Aug 06 09:24:06AM 	Aug 06 09:23:01AM 	
	Check Personal Email Accounts 	Success 	Aug 06 09:24:00AM 		Aug 06 09:24:04AM 	Aug 06 09:23:01AM 	
	Process Job Queue e0 	Success 	Aug 06 09:23:01AM 		Aug 06 09:23:03AM 	Aug 06 09:23:01AM 	
	Process Job Queue q1 	Success 	Aug 06 09:24:00AM 		Aug 06 09:24:03AM 	Aug 06 09:23:01AM 	
	Process Job Queue q0 	Success 	Aug 06 09:23:01AM 		Aug 06 09:23:03AM 	Aug 06 09:23:01AM`

**Comment by nmincone** [comment]
@lazespo Wow do I feel like a fool. I did resolve it. In my compose file I missed that the volume location for the daemon mount I prepared was incorrect.
Adding "./" in front of `volumes: - espocrm:/var/www/html` = `volumes:- ./espocrm:/var/www/html` fixed it!
