### ISSUE TITLE
Cannot see emails in Sent Folder - personal email account

### ISSUE THREAD

**Issue by stef204** [espocrm/espocrm-docker#47]
I have not yet been able to send an email via my espocrm test personal email account, but shouldn't I already be able to see the existing (previously) sent emails in the `Inbox.sent' folder of the IMAP account?

How does one configure that?

**Comment by stef204** [comment]
It looks ` espocrm` will only track email sent via `espocrm`, not the ones in the imap server's `Sent` folder (e.g. `INBOX.Sent`).

Is that correct?

PS Is the forum a better way of posting these issues?

**Comment by lazespo** [comment]
Hi @stef204,

This question is not related to EspoCRM installed specifically in Docker, but related to sent emails fetching in general. 

So, you are right, it is recommended to ask questions of this kind on the forum, where the community can explain to you in detail how this feature works.

**Comment by stef204** [comment]
OK, will switch to forum, thanks.
