### ISSUE TITLE
Persisting EspoCRM config between Upgrades (Docker)

### ISSUE THREAD

**Issue by stef204** [espocrm/espocrm-docker#52]
When I upgrade EspoCRM version via Dockerhub, so pull the `espocrm/espocrm:latest` or `espocrm/espocrm:{tag}` I then need to delete the container used by previous image and create a new one to run the upgraded image.

This seems to cause all EspoCRM settings (not the Mysql settings) to be lost:  currency, locale, smtp passwords, all of that has to be re-inserted, upon every upgrade.

Is there a way to have these settings persist across upgrades?

I use docker (not `docker-compose`.)

_Note: posted in the forum but no replies there._

**Comment by arkadiyasuratov** [comment]
Are you sure you are running the commands with volumes mounted? This is definitely an issue with your setup. Can you provide the exact step-by-step instructions with the commands on how you are setting up the containers?

**Comment by stef204** [comment]
I must be doing something wrong, note: I am new at docker.

How I started:

`docker pull expocrm/espocrm`

`docker run --name mysql -e MYSQL_ROOT_PASSWORD=password -d mysql:8`

`docker run --name my-espocrm -p 8085:80 --link mysql:mysql -d espocrm/espocrm`

This was the first time.

Then, for upgrades I have done this:

`docker pull espocrm/espocrm` or `docker pull espocrm/espocrm:8.3.0`

Then, and this is possibly where the problem occurs, if I run:

`docker run --name my-espocrm -p 8085:80 --link mysql:mysql -d espocrm/espocrm` docker gives me an error message that the container is already in use and please delete or rename it (something like that, I cannot find the exact error message in the logs).

So what I have to do is delete the container used by the previous version of EspoCRM, and then issue this command again to create a new container to run the upgraded (new) image:

`docker run --name my-espocrm -p 8085:80 --link mysql:mysql -d espocrm/espocrm`

Then when I log in, I have to redefine all of the parameters I mentioned in my original post.  It's a real PITA.

**Comment by arkadiyasuratov** [comment]
First, create a Docker volume:

```sh
docker volume create espocrm_data
```

Then, run the Docker container:

```sh
docker run --detach \
    --name espocrm \
    --volume espocrm_data:/var/www/html:rw \
    --publish 8085:80 \
    --link mysql:mysql \
    espocrm/espocrm:latest
```

### How to upgrade container:

1. Pull the latest image: 
```sh
docker pull espocrm/espocrm:latest
```

2. Stop and remove existing container:
```sh
docker stop espocrm; docker rm espocrm;
```

3. Start a new container:
```sh
docker run --detach \
    --name espocrm \
    --volume espocrm_data:/var/www/html:rw \
    --publish 8085:80 \
    --link mysql:mysql \
    espocrm/espocrm:latest
```

**Comment by stef204** [comment]
Thanks for your prompt feedback. I will follow your instructions and post the result here in a few hours.

**Comment by stef204** [comment]
Since I am fixing everything, I am also going to try to create a named volume, as opposed to the anonymous volume created at the beginning with `docker run --name mysql -e MYSQL_ROOT_PASSWORD=password -d mysql:8`.

Can you please give me the proper command line instructions to setup the `mysql` part (container and volume)?

I am thinking this line should do it? Or does it need to be modified?

`docker run --name mysql -e MYSQL_ROOT_PASSWORD=password --volume mysql:/var/lib/mysql -d mysql:8`

I will then copy over (using proper permissions, etc.) the content of the `_data` dir of the anonymous volume into the `_data` directory or the named volume `mysql`.

**Comment by arkadiyasuratov** [comment]
Yes, you need to create a volume first using the command `docker volume create mysql`.

Also, just a tip: the [`--link` flag is a legacy](https://docs.docker.com/network/links/) feature of Docker and may eventually be removed. I suggest the following:

1. Create a Docker network first
```sh
docker network create espocrm-net
```
2. Create Docker volumes for MySQL and EspoCRM
```sh
docker volume create mysql-data
docker volume create espocrm-data
```
3. Start MySQL container
```sh
docker run --detach \
    --name mysql \
    --network espocrm-net \
    --volume mysql-data:/var/lib/mysql:rw \
    --env MYSQL_ROOT_PASSWORD=password \
    mysql:8
```
4. Start EspoCRM container
```sh
docker run --detach \
    --name espocrm \
    --network espocrm-net \
    --volume espocrm-data:/var/www/html:rw \
    --publish 8085:80 \
    espocrm/espocrm:latest
```

**Comment by stef204** [comment]
@arkadiyasuratov 

Thank you very much for your help and support in fixing the problem.  I have reconfigured everything, created the new containers, network, volumes, etc.,properly; and all went fine on the first try.

All my data in the old mysql anonymous volume was properly copied into the new (named) volume without loss.

And I learned more about docker in the process--added bonus.

Thanks again.
